---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io

  - name: harbor
    url: https://helm.goharbor.io

  - name: stable
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.1.0
    namespace: cert-manager
    set:
      - installCRDs: true
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args: ["label", "namespace", "cert-manager", "certmanager.k8s.io/disable-validation=true"]

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 3.17.0
    namespace: ingress-nginx

  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.1.2
    values:
      - ../values/harbor-values.yaml