apiVersion: v1                            # Версия API
kind: Pod                                 # Объект, который создаем
metadata:
  name: web                               # Название Pod
  labels:                                 # Метки в формате key: value
    app: web
spec:                                     # Описание Pod
  initContainers:
  - name: html
    image: busybox:1.32.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  containers:                             # Описание контейнеров внутри Pod
  - name: web-server                      # Название контейнера
    image:   tjma/webserver:alpine-0.1    # Образ из которого создается контейнер
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}